{% set name = "tango-astor" %}
{% set version = "7.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/astor/-/archive/{{ version }}/astor-{{ version }}.tar.gz
  sha256: c446d90ce290828d4e3e739c1804b0d35a149fb08b90c5e73e43e962e0f1563b

build:
  number: 0

requirements:
  build:
    - openjdk 17
    - maven
  run:
    - openjdk >=17

test:
  commands:
    - test -f ${PREFIX}/share/java/Astor.jar             # [unix]
    - test -f ${PREFIX}/bin/astor                        # [unix]
    - if not exist %PREFIX%\share\java\Astor.jar exit 1  # [win]
    - if not exist %PREFIX%\Scripts\astor.bat exit 1     # [win]

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - aggregate-third-party-report.html
  summary: Astor is a graphical Tango control system administration tool.
  dev_url: https://gitlab.com/tango-controls/astor
  doc_url: https://tango-controls.readthedocs.io/en/latest/tools-and-extensions/built-in/astor/index.html

extra:
  recipe-maintainers:
    - beenje
